controllers:
  resource: ../../src/Controller/
  type: annotation

kernel:
  resource: ../../src/Kernel.php
  type: annotation

iam_api_controllers:
  resource: ../../srcIam/src/Adapter/Api/
  type: annotation