# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  ########################################################################################################################
  #
  #   Iam microservice
  #
  ########################################################################################################################
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "iam/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "iam - composer"
    labels:
      - "iam dependency"
    ignore:
      - dependency-name: "symfony/asset"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/browser-kit"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/cache"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/config"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/console"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/css-selector"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/debug-bundle"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/dependency-injection"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/dotenv"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/error-handler"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/event-dispatcher"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/filesystem"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/finder"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/framework-bundle"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/http-foundation"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/http-kernel"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/monolog-bridge"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/proxy-manager-bridge"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/routing"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/runtime"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/security-bundle"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/string"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/var-dumper"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/var-exporter"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/web-profiler-bundle"
        versions: [ "6.3.x","6.4.x"]
      - dependency-name: "symfony/yaml"
        versions: [ "6.3.x","6.4.x"]



  ########################################################################################################################
  #
  #   Customer microservice
  #
  ########################################################################################################################
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "customer/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "customer - composer"
    labels:
      - "customer dependency"
    ignore:
      - dependency-name: "symfony/browser-kit"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/cache"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/config"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/console"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/css-selector"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/dependency-injection"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/dotenv"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/error-handler"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/event-dispatcher"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/filesystem"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/finder"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/framework-bundle"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/http-foundation"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/http-kernel"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/monolog-bridge"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/phpunit-bridge"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/proxy-manager-bridge"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/routing"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/runtime"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/security-bundle"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/string"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/var-dumper"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/var-exporter"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/yaml"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]



########################################################################################################################
#
#   Blue microservice
#
########################################################################################################################
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "blue/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "blu - composer"
    labels:
      - "blue dependency"
    ignore:
      - dependency-name: "symfony/browser-kit"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/cache"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/config"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/console"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/css-selector"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/dependency-injection"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/dotenv"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/error-handler"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/event-dispatcher"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/filesystem"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/finder"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/framework-bundle"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/http-foundation"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/http-kernel"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/monolog-bridge"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/phpunit-bridge"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/proxy-manager-bridge"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/routing"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/runtime"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/security-bundle"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/string"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/var-dumper"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/var-exporter"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/yaml"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]


########################################################################################################################
#
#   Red microservice
#
########################################################################################################################
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "red/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "red - composer"
    labels:
      - "red dependency"
    ignore:
      - dependency-name: "symfony/browser-kit"
        versions: [ "6.3.x","6.4.x" ]
      - dependency-name: "symfony/cache"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/config"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/console"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/css-selector"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/dependency-injection"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/dotenv"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/error-handler"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/event-dispatcher"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/filesystem"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/finder"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/framework-bundle"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/http-foundation"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/http-kernel"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/proxy-manager-bridge"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/routing"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/runtime"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/security-bundle"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/string"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/var-dumper"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/var-exporter"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/web-profiler"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]
      - dependency-name: "symfony/yaml"
        versions: [ "6.2.x" ,"6.3.x","6.4.x"]


  ########################################################################################################################
  #
  #   Github Actions dependencies
  #
  ########################################################################################################################
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "github-actions"
    labels:
      - "GHA dependency"