# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  ########################################################################################################################
  #
  #   Iam microservice
  #
  ########################################################################################################################
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "iam/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "iam - composer"
    labels:
      - "iam dependency"
    ignore:
      - dependency-name: "symfony/*"
        versions: ["7.x"]


########################################################################################################################
#
#   Blue microservice
#
########################################################################################################################
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "blue/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "blu - composer"
    labels:
      - "blue dependency"
    ignore:
      - dependency-name: "symfony/*"
        versions: ["7.x"]
      - dependency-name: "*"
        update-types: ["version-update:semver-major","version-update:semver-minor"]

########################################################################################################################
#
#   Red microservice
#
########################################################################################################################
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "red/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "red - composer"
    labels:
      - "red dependency"
    ignore:
      - dependency-name: "symfony/*"
        versions: ["7.x"]


  ########################################################################################################################
  #
  #   Github Actions dependencies
  #
  ########################################################################################################################
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "github-actions"
    labels:
      - "GHA dependency"