services:


#########################################################################################################################
#########################################################################################################################
##
##   infra services
##
#########################################################################################################################
#########################################################################################################################



  ######################################################################################################################
  #
  #   Main database instance - Postgres
  #
  #   All microservices  share the same 'physical' database instance,
  #   but each microservice has a private schema/database.
  #
  ######################################################################################################################
  main-database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp


  ######################################################################################################################
  #
  #   api gateway - Traefik
  #
  ######################################################################################################################
  traefik:
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTP
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # WEB UI HTTP
      - target: 8080
        published: ${WEB_UI_HTTP_PORT:-8080}
        protocol: tcp
      # PROMETHEUS PORT
      - target: 8082
        published: 8082
        protocol: tcp


  ######################################################################################################################
  #
  #   Authentication & Authorization - Keycloak
  #
  ######################################################################################################################
  keycloak:
    environment:
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      # HTTP
      - target: 8080
        published: ${HTTP_PORT:-8888}
        protocol: tcp
      # HTTPS
      - target: 8443
        published: ${HTTPS_PORT:-8443}
        protocol: tcp
    command: ["start-dev", "--import-realm"]


  ######################################################################################################################
  #
  #   Messaging & queue - RabbitMq
  #
  ######################################################################################################################
  mbroker:
    ports:
      - target: 5672
        published: 5672
        protocol: tcp
      # HTTP
      - target: 15672
        published: ${RABBITMQ_HTTP_PORT:-15672}
        protocol: tcp

