workerman:
    servers:
        -
            name: 'Red service webserver'
            listen: http://0.0.0.0:80
            processes: 4

    reload_strategy:
        exception:
            active: true

        file_monitor:
            active: true
