controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

iam_api:
    resource: ../_iam/src/Adapter/Api/Auth/
    type: annotation