name: Blue service CD/CI

on:
  push:
    paths:
      - "blue/**"
      - '.github/workflows/blue-*.yaml'
jobs:
  commit-stage-workflow:
    name: Commit Stage
    uses: zerai/sycton/.github/workflows/blue-service-commit-stage.yaml@main
    with:
      triggering-sha: "${{ github.sha }}"

  acceptance-stage-workflow:
    name: Acceptance Stage
    needs:
      - commit-stage-workflow
    uses: zerai/sycton/.github/workflows/blue-service-acceptance-stage.yaml@main
    with:
      triggering-sha: "${{ github.sha }}"
