name: Blue - Acceptance stage

on:
  workflow_run:
    workflows:
      - Blue - Commit stage
    types:
      - completed

env:
  PHP_EXTENSIONS: ctype, iconv, json, curl, gd, intl, opcache, openssl, mbstring, mysql, pdo_sqlite
  PHP_EXTENSIONS_CACHE_KEY: cache-php-extensions-v1


defaults:
  run:
    shell: bash
    working-directory: blue


jobs:
  on-blue-commit-stage-success:
    runs-on: ubuntu-18.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - run: echo 'The triggering workflow passed'

      - name: Dump GHA Context
        uses: crazy-max/ghaction-dump-context@v1


  placeholder-dump-context:
    runs-on: ubuntu-18.04
    needs: [on-blue-commit-stage-success]
    timeout-minutes: 5
    strategy:
      matrix:
        php:
          - '8.0'
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: List directory
        run: ls -al